C
C  This file is part of MUMPS 5.3.4, released
C  on Mon Sep 28 07:16:41 UTC 2020
C
C
C  Copyright 1991-2020 CERFACS, CNRS, ENS Lyon, INP Toulouse, Inria,
C  Mumps Technologies, University of Bordeaux.
C
C  This version of MUMPS is provided to you free of charge. It is
C  released under the CeCILL-C license 
C  (see doc/CeCILL-C_V1-en.txt, doc/CeCILL-C_V1-fr.txt, and
C  https://cecill.info/licences/Licence_CeCILL-C_V1-en.html)
C
      SUBROUTINE DMUMPS_CONFIG_FILE_RETURN()
      RETURN
      END SUBROUTINE DMUMPS_CONFIG_FILE_RETURN
